### PR TITLE
An efficient multithreaded implementation of Max Clique Problem with Graph Degeneracy and Branch-and-Bound pattern

### PR DESCRIPTION
**Pull request by 0x0584**
The code is a mixture of various ideas I have absorbed from many white-papers I had read. Generally the algorithm runs as follow:

  * first we sort enumerate the vertices as keys, and sort them based on the colouring (greedy) of each vertex.

  * after that,
    1. *while* there are vertices and there still branches *do*
    2.   *read* the neighbours of each vertex
    3.   start a thread branching over the neighbours 
    4.   each time *pick* the highest-colour vertex `v` (most promising to be part of a max clique)
    5.   then *pop-up* the vertex `v` and look for all vertices that are adjacent to `v` in all other neighbours (recursively)
    6. when reaching an empty set of vertices, backtrack and pick vertices where there have been found a max clique (end of recursion tree, we may find a max clique if `size > old_size`)

### CODE REVIEW

**Comment by 0x0584** [comment]
_related [reposiory](https://github.com/0x0584/mc)_

**Comment by UnickSoft** [comment]
Hello.

Could you please add number threads as parameter? It allows planing processor loading.

**Comment by UnickSoft** [comment]
Also I noticed, what you use "not" in if operators. But it is not supported by Visual Studio, better use ! sing.

**Comment by 0x0584** [comment]
I will fix them sometime soon this weekend, is it worth to be merged?

**Comment by UnickSoft** [comment]
> I will fix them sometime soon this weekend, is it worth to be merged?

This looks great and works good. I am going to merge it, but i found one flaw: 
If I use xml report, the algorithm dublicates edges several times in report.
For example:
For graph: [graph_weight_test.txt](https://github.com/UnickSoft/GraphOffline/files/10714238/graph_weight_test.txt)
I call using command line:
`-mc graph_weight_test.txt  -threads 1 -report xml`
I got this result:
xml_report
How you can see some of eges are dublicated: 3-2 and 1-3
Could you please fix this problem with report?

**Comment by 0x0584** [comment]
I have just checked the PR, I will fix it ASAP

**Comment by UnickSoft** [comment]
Thanks for your work. I merged you PR and I will fix problem with edges duplications.

**Pull request merged**
